### ISSUE TITLE
singleCellExperiment not working

### ISSUE THREAD

**Issue by baj12** [RausellLab/CelliD#1] opened 2020-06-23 14:52 UTC
RunMCX is only working with Seurat object and not with SingleCellExperiment objects:

```
aa = as.SingleCellExperiment(seuratPbmc)
aa= RunMCA(aa, nmcs=5)
RunMCTSNE(aa, dims=seq(5), reduction = "MCA")

```

Error in `reducedDim<-`(`*tmp*`, reduction.name, value = cellEmb) : 
  invalid 'value' in 'reducedDim(<SingleCellExperiment>, type="character") <- value'
'value' should have number of rows equal to 'ncol(x)'

**Comment by Cortalak** [comment] 2020-07-19 10:36
Hello, sorry for the late reply and thanks for noticing that error.

I will update you as soon as this issue is fixed.

**Comment by Cortalak** [comment] 2020-07-19 12:15
Hi,

The issue is now fixed. Changed the code for MCX function which was grabbing wrong indexes for SingleCellExperiment object.
Thank you for pointing out this bug and again sorry for the late response.

**Closed by Cortalak** 2020-07-19 12:15 UTC
